[package]
name = "nature-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
rand = "0.8.5"
rand_distr = "0.4.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
